In [5]:
import numpy as np
x1= np.array([[1.0, 1.51], [1.2, 1.9], [2.2, 3.5]])
y1= np.array([[1, 2], [3, 4], [5, 6]])
z1= np.array([[ 0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j]])
print("Original array elements:")
print("x1",x1)
print("y1",y1)
print("z1",z1)
#print("Convert float values to integer values:")
# we can chnage it in any other format
#print(x1.astype(int))
print("size of x1",x1.size)
print("dimension of x1",x1.ndim)

print("size of y1",y1.size)
print("dimension of y1",y1.ndim)

print("size of z1",z1.size)
print("dimension of z1",z1.ndim)


Original array elements:
x1 [[1.   1.51]
 [1.2  1.9 ]
 [2.2  3.5 ]]
y1 [[1 2]
 [3 4]
 [5 6]]
z1 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
Convert float values to integer values:
size of x1 6
dimension of x1 2
size of y1 6
dimension of y1 2
size of z1 4
dimension of z1 2


In [11]:

matrix=np.array([[1,2,6],[3,4,7],[8,9,10]])
print("original")
print(matrix)
print("tranpose")
Transpose=matrix.T
print(Transpose)
inversion_matrix=np.linalg.inv(matrix)
print("INVERTED MATRIX")
print(inversion_matrix)
print("DOT PRODUCT")
DotProductMatrix=np.dot(matrix,Transpose)
matrix_new = print(DotProductMatrix)


original
[[ 1  2  6]
 [ 3  4  7]
 [ 8  9 10]]
tranpose
[[ 1  3  8]
 [ 2  4  9]
 [ 6  7 10]]
INVERTED MATRIX
[[ 23. -34.  10.]
 [-26.  38. -11.]
 [  5.  -7.   2.]]
DOT PRODUCT
[[ 41  53  86]
 [ 53  74 130]
 [ 86 130 245]]


In [22]:
# slicing

list1 =[i*2 for i in range(0,10)]

print(list1)
print(list1[:])
print(list1[0:])
print(list1[2:8])
# reversing the list
print(list1[::-1])
print(list1[10:0:-1])


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[4, 6, 8, 10, 12, 14]
[18, 16, 14, 12, 10, 8, 6, 4, 2, 0]
[18, 16, 14, 12, 10, 8, 6, 4, 2]


In [23]:
pip install wget

  Created wheel for wget: filename=wget-3.2-cp36-none-any.whl size=9682 sha256=98f9393bb2f5a91c99df8fd11817d339222b5d467f035e64ec39dec49b4f7d20
  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [27]:
import wget
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/DeepConnectAI/challenge-week-1/master/data/structured_data/data.csv'
#load of csv_file
filename = wget.download(url)
df = pd.read_csv(url)

array=np.array([df['Salary'],df['Age'],df['Country'],df['Price Category Of Purchase'],df['Purchased']])
print(array)

[[72000.0 48000.0 54000.0 61000.0 nan 58000.0 52000.0 79000.0 83000.0
  67000.0 54400.0 55000.0 58800.0 42000.0 41000.0 69000.0 67000.0 65000.0
  nan nan]
 [44.0 27.0 30.0 38.0 40.0 35.0 nan 48.0 50.0 37.0 18.0 22.0 nan 28.0
  24.0 35.0 32.0 38.0 45.0 25.0]
 ['France' 'Spain' 'Germany' 'Spain' 'Germany' 'France' 'Spain' 'France'
  'Germany' 'France' 'France' 'Germany' 'Germany' 'France' 'France'
  'Germany' 'Germany' 'Germany' 'France' 'Germany']
 [1 1 2 3 1 2 3 1 2 2 3 3 1 3 2 1 3 3 2 1]
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes'
  'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No']]
